
<div>
    <form data-mage-init='{"validation": {}}' action="<?=$this->getUrl('*/*/submit', ['_secure' => true])?>" class="form" id="dataForm" method="post">
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="fisrt_name"><span>First Name</span></label>
                <div class="control">
                    <input name="fisrt_name" id="fisrt_name" title="First Name" value=""  class="input-text" type="text" data-validate='{"required":true, "letters-only": true}'/>
                </div>
            </div>
            <div class="field name required">
                <label class="label" for="fisrt_name"><span>Last Name</span></label>
                <div class="control">
                    <input name="last_name" id="last_name" title="Last Name" value=""  class="input-text" type="text" data-validate='{"required":true, "letters-only": true}'/>
                </div>
            </div>
            <div class="field name required">
                <label class="label" for="fisrt_name"><span>Email</span></label>
                <div class="control">
                    <input name="email" id="email" title="Email" value=""  class="input-text" type="text" data-validate='{"required":true, "email": true}'/>
                </div>
            </div>
            <div class="field name required">
                <label class="label" for="fisrt_name"><span>Telephone</span></label>
                <div class="control">
                    <input name="telephone" id="telephone" title="Telephone" value=""  class="input-text" type="text" data-validate='{"required":true, "digits": true}'/>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="Submit" class="action submit primary">
                    <span>Submit</span>
                </button>
            </div>
            <div class="secondary">
                <a class="action check" type="button" href="<?=$this->getUrl('*/*/submit', ['_secure' => true])?>">
                    <span>Table</span>
                </a>
            </div>
        </div>
    </form>
</div>


<script type="text/x-magento-init">
    {
        "#dataForm": {
            "validation": {}
        }
    }
</script>