<form class="form col-12 row" method="post" name="DataForm" id="DataForm"
action="<?=$this->getUrl('*/*/submit', ['_secure' => true])?>">
    <div class="mb-3 col-md-6 row">
        <legend class="col-form-legend col-md-4">First Name</legend>
        <div class="col-md-8">
            <input type="text" class="form-control" name="fisrt_name" id="inputFirstName" placeholder="First Name">
        </div>
    </div>
    <div class="mb-3 col-md-6 row">
        <legend class="col-form-legend col-md-4">Last Name</legend>
        <div class="col-md-8">
            <input type="text" class="form-control" name="last_name" id="inputLastName" placeholder="Last Name">
        </div>
    </div>
    <div class="mb-3 col-md-6 row">
        <legend class="col-form-legend col-md-4">Email</legend>
        <div class="col-md-8">
            <input type="text" class="form-control" name="email" id="inputEmail" placeholder="Email">
        </div>
    </div>
    <div class="mb-3 col-md-6 row">
        <legend class="col-form-legend col-md-4">Telephone</legend>
        <div class="col-md-8">
            <input type="text" class="form-control" name="telephone" id="inputTelephone" placeholder="Telephone">
        </div>
    </div>
    <div class="mb-3 col-md-6 row text-center">
        <div class="offset-sm-4 col-sm-8">
            <button type="submit" class="btn btn-primary btn-lg" >Action</button>
        </div>
    </div>
</form>