
<?php
/**
 * @var \TresdTech\FinalProject\Block\Table $block
 */
 $collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('First Name') ?></th>
            <th scope="col" class="col name"><?php echo __('Last Name') ?></th>
            <th scope="col" class="col email"><?php echo __('Email') ?></th>
            <th scope="col" class="col telephone"><?php echo __('Telephone') ?></th>
            <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
 foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $item->getid() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('First Name')) ?>" class="col first_name">
                <?php echo $item->getfisrt_name() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Last Name')) ?>" class="col last_name">
                <?php echo $item->getlast_name() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Email')) ?>" class="col email">
                <?php echo $item->getemail() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Telephone')) ?>" class="col telephone">
                <?php echo $item->gettelephone() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <button onclick="window.location.href='<?=$this->getUrl('*/*/index', ['_secure' => true])?>'" class="btn btn-primary btn-lg" >Formulario</button>
</div>
<?php
 }
 else { 
 ?>
 <h1>"No hay registros"</h1>
 <button onclick="window.location.href='<?=$this->getUrl('*/*/index', ['_secure' => true])?>'" class="btn btn-primary btn-lg" >Formulario</button>
 <?php } ?>